// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfxdyshvyjjalfgcipnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmeGR5c2h2eWpqYWxmZ2NpcG5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MjU0NDMsImV4cCI6MjA2MTUwMTQ0M30.WUpE-o5f8Wfy1XI5FCcFsspDJWblkwhY075kQ6PVCQE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);